/**
 * REGISTER EXPENSES MUTATIONS
 */
export const LIST_EXPENSES = 'LIST_EXPENSES';
// export const EXPENSE_DETAIL = 'EXPENSE_DETAIL';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const UPDATE_RECEIPT_TO_EXPENSE = 'UPDATE_RECEIPT_TO_EXPENSE';
