export const SET_EXPENSE_LIST = "SET_EXPENSE_LIST";
export const SET_EXPENSE = "SET_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const SET_EXPENSE_STATUS = "SET_EXPENSE_STATUS";

// Loading Indicators
export const EXPENSES_LOADING = "EXPENSES_LOADING";
export const EXPENSE_LOADING = "EXPENSE_LOADING";
